### ISSUE TITLE
Investigate why ConfigMaps need to be fetched with "default" namespace when no namespace is specfied

### ISSUE THREAD

**Issue by fghimpeteanu-ionos** [ionos-cloud/crossplane-provider-ionoscloud#184]
### What problem are you facing?

When we want to fetch a ConfigMap using the k8s client provided by crossplane-provider we need to use the namespace "default", if the ConfigMap was created without specifying a namespace:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-lease
data:
  key: "value"
```

However there is no problem when we fetch our CRs using the k8s client.
