### ISSUE TITLE
Unable to create a cubeserver

### ISSUE THREAD

**Issue by hoffmannmario** [ionos-cloud/crossplane-provider-ionoscloud#188]
### What happened?

Hello, 
I wanted to get started with the crossplane provider and started with the examples[1]. After I set everything up I wanted to create a datacenter with a cubeserver in it.
When I execute these two commands, everything seems to work as expected (yaml attached below):
```
$ kubectl apply -f tmpdatacenter.yaml
datacenter.compute.ionoscloud.crossplane.io/example created
$ kubectl apply -f tmpcube.yaml
cubeserver.compute.ionoscloud.crossplane.io/examplecubeserver created
```

The datacenter gets created correctly in the cloud, but the cubeserver does not seem to get synced. Upod further investigation I ran ```$ kubectl get cubeserver -o yaml```, which shows me this error:
```
[...]
    - lastTransitionTime: "2024-03-27T09:49:41Z"
      message: |-
        create failed: failed to create cube server. error: 422 Unprocessable Entity {
          "httpStatus" : 422,
          "messages" : [ {
            "errorCode" : "200",
            "message" : "[VDC-5-1921] The attribute 'cpuFamily' must not be provided for Cube servers."
          } ]
        }
[...]
```

But if I leave the cpuFamily attribute out, I get another error:
```"message" : "[(root).properties.cpuFamily] Attribute value '' not allowed. Expected one of [AMD_OPTERON, AMD_EPYC, INTEL_SKYLAKE, INTEL_XEON, INTEL_ICELAKE]" ```

### How can we reproduce it?

I guess apply those yaml files?

### What environment did it happen in?
Crossplane Provider IONOS Cloud version: ghcr.io/ionos-cloud/crossplane-provider-ionoscloud:latest (as of 27th march, I guess v1.0.10?)

* Client Version: v1.29.3
* Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
* Server Version: v1.29.2
* OS: Ubuntu 22.04 WSL
* Kernel: Linux A001320623 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

## Additional Notes

datacenter.yaml:
```
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: example
managementPolicies:
  - "*"
spec:
  forProvider:
    name: exampleDatacenter
    location: de/txl
    description: test
  providerConfigRef:
    name: example
```

cube.yaml:
```
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: CubeServer
metadata:
  name: examplecubeserver
managementPolicies:
  - "*"
spec:
  forProvider:
    name: exampleCubeServer
    availabilityZone: AUTO
    template:
      name: 1-2-30
    volume:
      name: exampleDasVolume
      bus: VIRTIO
      licenceType: LINUX
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
```

## References

- [1] https://docs.ionos.com/crossplane-provider/example

Kind regards
