### ISSUE TITLE
regression in creation of mk8s nodepools

### ISSUE THREAD

**Issue by leroyshirto** [ionos-cloud/crossplane-provider-ionoscloud#255]
### What happened?
There has been a reversion in functionallity. The fix implemented in PR https://github.com/ionos-cloud/crossplane-provider-ionoscloud/pull/243 appears to have been reverted by this recent PR: https://github.com/ionos-cloud/crossplane-provider-ionoscloud/pull/249/files#diff-58333b86186aa1a8ee33021762db2493a983b22ad698c96a8c1377a877eb81c6R323

The result of this is NodePool lan config which only rely on lanCondig e.g

```yaml
lans:
- dhcp: true
  lanConfig:
    lanIdRef:
      name: my-lan
```

Will now result in an error as datacenterId will be set to empty string ""
