### ISSUE TITLE
Cluster autoscaling works against NodePool `nodeCount`

### ISSUE THREAD

**Issue by schaschko** [ionos-cloud/crossplane-provider-ionoscloud#296]
## Cluster autoscaling works against NodePool `nodeCount`

If cluster autoscaling is enabled, e.g.

```yaml
apiVersion: k8s.ionoscloud.crossplane.io/v1alpha1
kind: NodePool
spec:
  forProvider:
    nodeCount: 3
    autoScaling:
      maxNodeCount: 8
      minNodeCount: 1
    # ...
```

Crossplane will work against Cluster Autoscaler.

If you put load on the nodes, autoscaler kicks in and scales up the nodes in the nodepool. On reconcile Crossplane notices that, and tries to enforce the `nodeCount`.

You can observe this in e.g. in the `NodePool` resource, where it will first
scale up:

```yaml
status:
  atProvider:
    nodeCount: 8
```

Then Crossplane notices and enforces to scale down:

```yaml
status:
  atProvider:
    nodeCount: 3
```

Therefore the `NodePool` won't come to a rest `state: UPDATING` for a while, which also causes wild rescheduling of the pods during that period and then Cluster Autoscaler to fail e.g.

```text
cluster-autoscaler  pod didn't trigger scale-up: 1 in backoff after failed scale-up
```

After a while, the cycle starts again making the number of nodes oscillate over time.

## Possible solution

Crossplane defines [initProvider](https://docs.crossplane.io/latest/concepts/managed-resources/#initprovider), which is intended to be used for cases like these. E.g. you could define then:

```yaml
apiVersion: k8s.ionoscloud.crossplane.io/v1alpha1
kind: NodePool
spec:
  initProvider:
    nodeCount: 3
  forProvider:
    autoScaling:
      maxNodeCount: 8
      minNodeCount: 1
      # ...
```

Can you please look into that?
